name: Publish and Release

on:
  push:
    branches:
      - master

jobs:
  publish-and-release:
    if: github.repository == 'champkeh/vue3-deno-deploy'
    runs-on: ubuntu-latest
    environment: Deno Deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Build app
        run: npm run build
